In [6]:
import os
import sys
import pathlib
import pandas as pd
import numpy as np
import geopandas as gpd
import matsim
import importlib

# Config

In [49]:
PROJECT_ROOT = pathlib.Path.cwd()
GENERAL_TOOL_PATH = PROJECT_ROOT / "python" / "tools"

SCENARIOS_DIR = PROJECT_ROOT / "output" / "collabReceiverDistantCarrier" / "grid20x20"
# Add the general tool path to the system path
if str(GENERAL_TOOL_PATH) not in sys.path:
    sys.path.append(str(GENERAL_TOOL_PATH))

In [35]:
import matsim_freight_output_reader
importlib.reload(matsim_freight_output_reader)

# Utils

In [62]:
def derive_scenario_param_from_name(scenario_name):
    """
    Derives the scenario parameter from the scenario name.
    """
    split_name = scenario_name.split('-')
    depot_loc = split_name[0][:4]

    return (depot_loc)

In [56]:
def load_agg_results(scenarios_dir):
    scenarios = matsim_freight_output_reader.discover_output_scenarios(scenarios_dir)
    ''' For-loop to load and process all the results from each scenario '''
    for scenario in scenarios.itertuples():
        scenario_results = matsim_freight_output_reader.read_scenario_output(scenario.scenario_path)

        vehicles = scenario_results['events']['vehicle_summary']
        vehicles['carrier'] = (vehicles['vehicle_id'].str.split('_').apply(lambda parts: next((p for p in parts if p.startswith('carrier')), None)))

        break

    return vehicles

In [57]:
load_agg_results(SCENARIOS_DIR)

,vehicle_id,event_count,first_event_time,last_event_time,simulation_span_s,pickup_count,delivery_count,activity_event_count,tour_count,tour_time_s,traffic_leg_count,transit_time_s,link_count,unique_link_count,vkt_m,vkt_km,non_transit_tour_time_s,carrier
0,freight_carrier1_veh_lightVan1_1,142,21600.0,29938.0,8338.0,5,5,22,1,8338.0,11,2328.0,17,16,17000.0,17.0,6010.0,carrier1
1,freight_carrier1_veh_lightVan1_2,134,21600.0,29578.0,7978.0,5,5,22,1,7978.0,11,1968.0,13,12,13000.0,13.0,6010.0,carrier1

In [63]:
derive_scenario_param_from_name('dc00_center-clustered-centeredChessboardArea-penSweep-af0.80-p0.0014-exactShapley-i00')

'dc00'

# Test

In [51]:
matsim_freight_output_reader.discover_output_scenarios(SCENARIOS_DIR)

,scenario_name,scenario_path,events_path,receivers_path,carriers_path,collaboration_path,network_path
0,dc00_center-clustered-centeredChessboardArea-p...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/dat...
1,dc00_center-clustered-centeredChessboardArea-p...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/dat...
2,dc00_center-clustered-centeredChessboardArea-p...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/dat...
3,dc00_center-clustered-centeredChessboardArea-p...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/dat...
4,dc00_center-clustered-centeredChessboardArea-p...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/dat...
...,...,...,...,...,...,...,...
595,dc09_bottom-dispersed-centeredChessboardArea-p...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/dat...
596,dc09_bottom-dispersed-centeredChessboardArea-p...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/dat...
597,dc09_bottom-dispersed-centeredChessboardArea-p...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/dat...
598,dc09_bottom-dispersed-centeredChessboardArea-p...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/dat...
599,dc09_bottom-dispersed-centeredChessboardArea-p...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/out...,/Volumes/External/gitProj/matsim-libs-2024/dat...

In [39]:
scenario = (
    "output/collabReceiverDistantCarrier/grid20x20/"
    "dc09_bottom-dispersed-centeredChessboardArea-penSweep-af0.80-p0.0056-exactShapley-i09"
)

result = matsim_freight_output_reader.read_scenario_output(scenario)

chains = result["events"]["travel_chains"]
vehicles = result["events"]["vehicle_summary"]
tours = result["events"]["tours"]
shipments = result["events"]["shipments"]

receivers = result["receivers"]["receivers"]
last_iter_receivers = result["last_iter_receivers"]["receivers"]
carriers = result["carriers"]["carriers"]
iter0_carriers = result["iter0_carriers"]["carriers"]
last_iter_carriers = result["last_iter_carriers"]["carriers"]
allocations = result["collaboration"]["allocations"]
network_links = result["network"]["links"]

In [40]:
result['collaboration'].keys()

dict_keys(['metadata', 'coalitions', 'coalition_members', 'subcoalitions', 'subcoalition_members', 'allocations'])

In [34]:
result['collaboration']['allocations']

    allocation_index collaboratorId       value
0                  0    receiver_09   36.452057
1                  1    receiver_08   54.691592
2                  2    receiver_05   69.255620
3                  3       carrier1  171.351972
4                  4    receiver_04   76.209265
5                  5    receiver_07   66.345010
6                  6    receiver_06   70.789393
7                  7    receiver_01   67.225478
8                  8    receiver_00   81.646973
9                  9    receiver_03   78.248090
10                10    receiver_02   84.544413

In [15]:
chains

,vehicle_id,chain_position,event_index,time,type,event_category,link,actType,act_type,tour_id,...,networkMode,relativePosition,carrierId,tourId,shipmentId,pickupDuration,capacityDemand,dropoffDuration,is_freight_event,link_length_m
0,freight_carrier1_veh_lightVan1_1,0,6,21600.0,actend,activity,"j(10,1)R",start,start,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,1000.0
1,freight_carrier1_veh_lightVan1_1,1,7,21600.0,departure,other,"j(10,1)R",NaN,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,1000.0
2,freight_carrier1_veh_lightVan1_1,2,8,21600.0,PersonEntersVehicle,vehicle_occupancy,NaN,NaN,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN
3,freight_carrier1_veh_lightVan1_1,3,11,21600.0,vehicle enters traffic,movement,"j(10,1)R",NaN,NaN,1,...,car,1.0,NaN,NaN,NaN,NaN,NaN,NaN,True,1000.0
4,freight_carrier1_veh_lightVan1_1,4,13,21600.0,vehicle leaves traffic,movement,"j(10,1)R",NaN,NaN,1,...,car,1.0,NaN,NaN,NaN,NaN,NaN,NaN,True,1000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,freight_carrier1_veh_lightVan1_3,137,409,30390.0,vehicle leaves traffic,movement,"j(10,1)R",NaN,NaN,3,...,car,1.0,NaN,NaN,NaN,NaN,NaN,NaN,True,1000.0
458,freight_carrier1_veh_lightVan1_3,138,410,30390.0,PersonLeavesVehicle,vehicle_occupancy,NaN,NaN,NaN,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN
459,freight_carrier1_veh_lightVan1_3,139,411,30390.0,arrival,other,"j(10,1)R",NaN,NaN,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,1000.0
460,freight_carrier1_veh_lightVan1_3,140,412,30390.0,actstart,activity,"j(10,1)R",end,end,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,1000.0
461,freight_carrier1_veh_lightVan1_3,141,413,30390.0,Freight tour ends,tour,"j(10,1)R",NaN,tour_end,3,...,NaN,NaN,carrier1,3,NaN,NaN,NaN,NaN,True,1000.0

In [16]:
vehicles

,vehicle_id,event_count,first_event_time,last_event_time,simulation_span_s,pickup_count,delivery_count,activity_event_count,tour_count,tour_time_s,traffic_leg_count,transit_time_s,link_count,unique_link_count,vkt_m,vkt_km,non_transit_tour_time_s
0,freight_carrier1_veh_lightVan1_1,178,21600.0,33023.0,11423.0,4,4,18,1,11423.0,9,5896.0,45,44,45000.0,45.0,5527.0
1,freight_carrier1_veh_lightVan1_2,142,21600.0,30030.0,8430.0,3,3,14,1,8430.0,7,4824.0,37,36,37000.0,37.0,3606.0
2,freight_carrier1_veh_lightVan1_3,142,21600.0,30390.0,8790.0,3,3,14,1,8790.0,7,4824.0,37,36,37000.0,37.0,3966.0

In [20]:
tours

,vehicle_id,tour_id,carrier_id,tour_start_time,tour_end_time,tour_duration_s,start_link,end_link,event_count,pickup_count,delivery_count,is_complete,transit_time_s,traffic_leg_count,link_count,vkt_m,vkt_km
0,freight_carrier1_veh_lightVan1_1,1,carrier1,21600.0,33023.0,11423.0,"j(10,1)R","j(10,1)R",178,4,4,True,5896.0,9,45,45000.0,45.0
1,freight_carrier1_veh_lightVan1_2,2,carrier1,21600.0,30030.0,8430.0,"j(10,1)R","j(10,1)R",142,3,3,True,4824.0,7,37,37000.0,37.0
2,freight_carrier1_veh_lightVan1_3,3,carrier1,21600.0,30390.0,8790.0,"j(10,1)R","j(10,1)R",142,3,3,True,4824.0,7,37,37000.0,37.0

In [41]:
iter0_carriers

,carrier_id,id,selected_plan_score,capabilities_fleetSize,vehicle_count,shipment_count,service_count,plan_count,selected_plan_index,selected_plan_attribute_jspritScore
0,carrier1,carrier1,-573.0512,INFINITE,2,10,0,1,0,-1403.666667

In [17]:
carriers

,carrier_id,id,selected_plan_score,capabilities_fleetSize,vehicle_count,shipment_count,service_count,plan_count,selected_plan_index,selected_plan_attribute_jspritScore
0,carrier1,carrier1,-401.14569,INFINITE,2,10,0,1,0,-741.933333

In [42]:
last_iter_carriers

,carrier_id,id,selected_plan_score,capabilities_fleetSize,vehicle_count,shipment_count,service_count,plan_count,selected_plan_index,selected_plan_attribute_jspritScore
0,carrier1,carrier1,-401.14569,INFINITE,2,10,0,1,0,-741.933333

In [19]:
receivers

,receiver_id,id,linkId,selected_plan_score,attribute_collaborationStatus,attribute_grandCoalitionMember,attribute_score,attribute_twCost,plan_count,selected_plan_index,selected_time_window_start,selected_time_window_end,selected_time_window_start_s,selected_time_window_end_s
0,receiver_00,receiver_00,"i(10,10)",-44.320758,True,True,-44.320758,1,5,3,06:00:00,08:00:00,21600.0,28800.0
1,receiver_01,receiver_01,"j(7,11)",-43.366696,True,True,-43.366696,1,5,1,06:00:00,08:00:00,21600.0,28800.0
2,receiver_02,receiver_02,"i(13,10)",-44.250080,True,True,-44.250080,1,5,1,06:00:00,08:00:00,21600.0,28800.0
3,receiver_03,receiver_03,"j(9,9)",-43.407389,True,True,-43.407389,1,5,1,06:00:00,08:00:00,21600.0,28800.0
4,receiver_04,receiver_04,"j(11,13)",-45.135961,True,True,-45.135961,1,5,1,06:00:00,08:00:00,21600.0,28800.0
5,receiver_05,receiver_05,"i(5,7)R",-52.876949,True,True,-65.533266,1,5,1,06:00:00,08:00:00,21600.0,28800.0
6,receiver_06,receiver_06,"i(5,11)R",-44.125631,True,True,-44.125631,1,5,1,06:00:00,08:00:00,21600.0,28800.0
7,receiver_07,receiver_07,"i(14,7)R",-46.672530,True,True,-46.672530,1,5,0,06:00:00,08:00:00,21600.0,28800.0
8,receiver_08,receiver_08,"i(5,14)",-62.228966,True,True,-62.228966,1,5,0,06:00:00,08:00:00,21600.0,28800.0
9,receiver_09,receiver_09,"j(8,6)R",-77.150834,True,True,-77.150834,1,4,1,06:00:00,08:00:00,21600.0,28800.0

In [45]:
receivers['selected_plan_score'].sum()

np.float64(-503.5357929493639)

In [43]:
last_iter_receivers

,receiver_id,id,linkId,selected_plan_score,attribute_collaborationStatus,attribute_grandCoalitionMember,attribute_score,attribute_twCost,plan_count,selected_plan_index,selected_time_window_start,selected_time_window_end,selected_time_window_start_s,selected_time_window_end_s
0,receiver_00,receiver_00,"i(10,10)",-38.513027,True,True,-38.513027,1,5,3,06:00:00,08:00:00,21600.0,28800.0
1,receiver_01,receiver_01,"j(7,11)",-52.934522,True,True,-52.934522,1,5,1,06:00:00,08:00:00,21600.0,28800.0
2,receiver_02,receiver_02,"i(13,10)",-35.615587,True,True,-35.615587,1,5,1,06:00:00,08:00:00,21600.0,28800.0
3,receiver_03,receiver_03,"j(9,9)",-41.911910,True,True,-41.911910,1,5,1,06:00:00,08:00:00,21600.0,28800.0
4,receiver_04,receiver_04,"j(11,13)",-43.950735,True,True,-43.950735,1,5,1,06:00:00,08:00:00,21600.0,28800.0
5,receiver_05,receiver_05,"i(5,7)R",-50.904380,True,True,-50.904380,1,5,1,06:00:00,08:00:00,21600.0,28800.0
6,receiver_06,receiver_06,"i(5,11)R",-49.370607,True,True,-49.370607,1,5,1,06:00:00,08:00:00,21600.0,28800.0
7,receiver_07,receiver_07,"i(14,7)R",-53.814990,True,True,-53.814990,1,5,0,06:00:00,08:00:00,21600.0,28800.0
8,receiver_08,receiver_08,"i(5,14)",-65.468408,True,True,-65.468408,1,5,0,06:00:00,08:00:00,21600.0,28800.0
9,receiver_09,receiver_09,"j(8,6)R",-83.707943,True,True,-83.707943,1,4,1,06:00:00,08:00:00,21600.0,28800.0

In [44]:
last_iter_receivers['selected_plan_score'].sum()

np.float64(-516.1921100000013)

In [46]:
allocations

    allocation_index collaboratorId       value
0                  0    receiver_09   36.452057
1                  1    receiver_08   54.691592
2                  2    receiver_05   69.255620
3                  3       carrier1  171.351972
4                  4    receiver_04   76.209265
5                  5    receiver_07   66.345010
6                  6    receiver_06   70.789393
7                  7    receiver_01   67.225478
8                  8    receiver_00   81.646973
9                  9    receiver_03   78.248090
10                10    receiver_02   84.544413

In [47]:
network_links

,length,freespeed,capacity,permlanes,oneway,modes,link_id,from_node,to_node,from_x,from_y,to_x,to_y,euclidean_length_m,free_flow_travel_time_s,modes_list
0,1000.0,7.5,10.0,1.0,1,car,"i(1,0)","(0,0)","(1,0)",0.0,0.0,1000.0,0.0,1000.0,133.333333,"(car,)"
1,1000.0,7.5,10.0,1.0,1,car,"i(1,1)R","(1,1)","(0,1)",1000.0,1000.0,0.0,1000.0,1000.0,133.333333,"(car,)"
2,1000.0,7.5,10.0,1.0,1,car,"i(1,10)","(0,10)","(1,10)",0.0,10000.0,1000.0,10000.0,1000.0,133.333333,"(car,)"
3,1000.0,7.5,10.0,1.0,1,car,"i(1,11)R","(1,11)","(0,11)",1000.0,11000.0,0.0,11000.0,1000.0,133.333333,"(car,)"
4,1000.0,7.5,10.0,1.0,1,car,"i(1,12)","(0,12)","(1,12)",0.0,12000.0,1000.0,12000.0,1000.0,133.333333,"(car,)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
835,1000.0,7.5,10.0,1.0,1,car,"j(9,5)","(9,4)","(9,5)",9000.0,4000.0,9000.0,5000.0,1000.0,133.333333,"(car,)"
836,1000.0,7.5,10.0,1.0,1,car,"j(9,6)","(9,5)","(9,6)",9000.0,5000.0,9000.0,6000.0,1000.0,133.333333,"(car,)"
837,1000.0,7.5,10.0,1.0,1,car,"j(9,7)","(9,6)","(9,7)",9000.0,6000.0,9000.0,7000.0,1000.0,133.333333,"(car,)"
838,1000.0,7.5,10.0,1.0,1,car,"j(9,8)","(9,7)","(9,8)",9000.0,7000.0,9000.0,8000.0,1000.0,133.333333,"(car,)"
839,1000.0,7.5,10.0,1.0,1,car,"j(9,9)","(9,8)","(9,9)",9000.0,8000.0,9000.0,9000.0,1000.0,133.333333,"(car,)"

In [12]:
scenarios = matsim_freight_output_reader.discover_output_scenarios(
    "output/collabReceiverDistantCarrier/grid20x20"
)

# only read the network once, since it is the same for all scenarios
network = matsim_freight_output_reader.read_network(scenarios.iloc[0]["network_path"])

vehicle_results = []

for scenario in scenarios.itertuples():
    events = matsim_freight_output_reader.read_freight_events(
        scenario.events_path,
        network=network,
    )

    summary = events["vehicle_summary"].assign(
        scenario_name=scenario.scenario_name
    )
    vehicle_results.append(summary)

all_vehicle_results = pd.concat(vehicle_results, ignore_index=True)

In [13]:
all_vehicle_results

,vehicle_id,event_count,first_event_time,last_event_time,simulation_span_s,pickup_count,delivery_count,activity_event_count,tour_count,tour_time_s,traffic_leg_count,transit_time_s,link_count,unique_link_count,vkt_m,vkt_km,non_transit_tour_time_s,scenario_name
0,freight_carrier1_veh_lightVan1_1,142,21600.0,29938.0,8338.0,5,5,22,1,8338.0,11,2328.0,17,16,17000.0,17.0,6010.0,dc00_center-clustered-centeredChessboardArea-p...
1,freight_carrier1_veh_lightVan1_2,134,21600.0,29578.0,7978.0,5,5,22,1,7978.0,11,1968.0,13,12,13000.0,13.0,6010.0,dc00_center-clustered-centeredChessboardArea-p...
2,freight_carrier1_veh_lightVan1_1,142,21600.0,29754.0,8154.0,5,5,22,1,8154.0,11,2144.0,17,16,17000.0,17.0,6010.0,dc00_center-clustered-centeredChessboardArea-p...
3,freight_carrier1_veh_lightVan1_2,150,21600.0,30650.0,9050.0,5,5,22,1,9050.0,11,2680.0,21,18,21000.0,21.0,6370.0,dc00_center-clustered-centeredChessboardArea-p...
4,freight_carrier1_veh_lightVan1_1,142,21600.0,29938.0,8338.0,5,5,22,1,8338.0,11,2144.0,17,16,17000.0,17.0,6194.0,dc00_center-clustered-centeredChessboardArea-p...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1412,freight_carrier1_veh_lightVan1_2,178,21600.0,33023.0,11423.0,4,4,18,1,11423.0,9,5896.0,45,44,45000.0,45.0,5527.0,dc09_bottom-dispersed-centeredChessboardArea-p...
1413,freight_carrier1_veh_lightVan1_3,118,21600.0,28782.0,7182.0,3,3,14,1,7182.0,7,3216.0,25,24,25000.0,25.0,3966.0,dc09_bottom-dispersed-centeredChessboardArea-p...
1414,freight_carrier1_veh_lightVan1_1,178,21600.0,33023.0,11423.0,4,4,18,1,11423.0,9,5896.0,45,44,45000.0,45.0,5527.0,dc09_bottom-dispersed-centeredChessboardArea-p...
1415,freight_carrier1_veh_lightVan1_2,142,21600.0,30030.0,8430.0,3,3,14,1,8430.0,7,4824.0,37,36,37000.0,37.0,3606.0,dc09_bottom-dispersed-centeredChessboardArea-p...
1416,freight_carrier1_veh_lightVan1_3,142,21600.0,30390.0,8790.0,3,3,14,1,8790.0,7,4824.0,37,36,37000.0,37.0,3966.0,dc09_bottom-dispersed-centeredChessboardArea-p...